name: Release Build

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: true

jobs:

  build_release:

    name: Build on windows-latest (win-x64)
    runs-on: windows-latest

    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore NuGet packages
        run: dotnet restore RunCat365.sln

      - name: Publish RunCat365 project
        run: dotnet publish RunCat365/RunCat365.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true --output ./publish

      - name: (DEBUG) List published files
        run: Get-ChildItem -Path ./publish | Format-Table Name, Length

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RunCat365-win-x64
          path: |
            "./publish/RunCat365.exe"
            "./publish/RunCat365.pdb"
            "./publish/RunCat365.config"

      - name: Generate build info
        id: var
        run: |
          echo "full_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  recreate_release:
    name: Recreate Release
    runs-on: ubuntu-latest
    needs: build_release
    steps:
      - uses: actions/checkout@v4

      - name: Delete existing release
        id: delete_release
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag = "release";

            const releases = await github.rest.repos.listReleases({owner: owner, repo: repo});
            const release = releases.data.find(release => release.tag_name === tag);

            if (release) {
              await github.rest.repos.deleteRelease({owner: owner, repo: repo, release_id: release.id});
              console.log(`Deleted release with ID ${release.id}`);
            } else {
              console.log("No existing release found");
            }

            try {
              await github.rest.git.deleteRef({owner: owner, repo: repo, ref: `tags/${tag}`});
              console.log(`Deleted tag ${tag}`);
            } catch {
              console.log(`No tag ${tag} to delete`);
            }

      - name: Download all artifacts into subfolders
        uses: actions/download-artifact@v4
        with:
          path: ./release_files

      - name: Calculate SHA256 checksums
        id: build_sha
        run: |
          checksums=""
          for file in ./release_files/RunCat365-win-x64/*; do
            if [ -f "$file" ]; then
              hash=$(sha256sum "$file" | awk '{ print $1 }')
              checksums+="**$(basename "$file")**: \`$hash\`"$'\n'
            fi
          done
          if [ -n "$checksums" ]; then
            checksums=${checksums%$'\n'}
          fi
          echo "checksums<<EOF" >> $GITHUB_OUTPUT
          echo -e "$checksums" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or update release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: release
          name: Release [${{ needs.build_release.outputs.short_sha }}]
          body: |
            **🤖 This release build was generated automatically by GitHub Actions.**
            [Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            🛡 SHA256 checksums:
            ${{ steps.build_sha.outputs.checksums }}

            You can download the attached artifacts to test the latest build.
            ⚠️ Build artifacts **ARE NOT** guaranteed to be **IDENTICAL** to release assets, as release assets can be modified after they are uploaded.

            📝 Full Commit Hash:
            ```
            ${{ needs.build_release.outputs.full_sha }}
            ```
            
          files: ./release_files/**/*